# Generated by Django 4.2.5 on 2023-10-02 08:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0003_event_remove_order_time_order_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferoom',
            name='close_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='conferoom',
            name='open_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
