# Generated by Django 4.2.5 on 2023-10-02 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0006_timeslot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
