# Generated by Django 4.2.5 on 2023-10-02 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
