# Generated by Django 4.2.5 on 2023-10-23 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0009_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room_timezone',
            field=models.CharField(default='UTC', max_length=63),
        ),
    ]
