# Generated by Django 4.2.5 on 2023-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0010_order_room_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferoom',
            name='timezone',
            field=models.CharField(default='Your_Default_Timezone', max_length=50),
        ),
    ]
