# Generated by Django 4.2.5 on 2023-11-08 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0011_conferoom_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.CharField(max_length=10),
        ),
    ]
