# Generated by Django 4.2.5 on 2023-11-08 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0012_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='room_timezone',
        ),
        migrations.AddField(
            model_name='order',
            name='checkdig',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.CreateModel(
            name='check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('check_time', models.DateTimeField(blank=True, null=True)),
                ('checkdig', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur.conferoom')),
            ],
        ),
    ]
