# Generated by Django 4.2.5 on 2023-11-08 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dinosaur', '0013_remove_order_room_timezone_order_checkdig_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='user',
        ),
        migrations.AddField(
            model_name='check',
            name='cardid',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
