# Generated by Django 4.2.5 on 2023-11-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0014_remove_check_user_check_cardid_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cardid',
            field=models.CharField(default='123456789', max_length=20),
        ),
    ]
