# Generated by Django 4.2.5 on 2023-11-10 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0015_order_cardid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='checkdig',
        ),
        migrations.AlterField(
            model_name='check',
            name='room',
            field=models.CharField(default='電話亭', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='cardid',
            field=models.CharField(default='', max_length=20),
        ),
    ]
