# Generated by Django 4.2.5 on 2023-11-11 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0016_remove_check_checkdig_alter_check_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dinosaur.conferoom'),
        ),
    ]
