# Generated by Django 4.2.7 on 2023-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0017_alter_check_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferoom',
            name='room_status',
            field=models.CharField(default='VACANT', max_length=15),
        ),
    ]
