# Generated by Django 4.2.7 on 2023-11-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dinosaur', '0018_conferoom_room_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferoom',
            name='room_status',
            field=models.CharField(default='☑', max_length=2),
        ),
    ]
